In [21]:
import keras
import numpy as np

from sklearn. datasets import load_iris

X, y = load_iris ( return_X_y =True)

In [4]:
X.shape

(150, 4)

In [6]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [7]:
y.shape

(150,)

In [8]:
y[-10:] # classes staan geordend

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Dataset heeft 4 features en 3 classes.

5 neuronen in de verborgen laag.

In [14]:
def get_model():
  model = keras.models.Sequential() # lagen één voor één uitvoeren (input, verborgen en output)

  # Lagen toevoegen
  model.add(keras.layers.Input(shape=(4,), name="input_layer"))
  model.add(keras.layers.Dense(units=5, activation="relu", name="hidden_layer")) # volledig geconnecteerde laag
  model.add(keras.layers.Dense(units=3, activation="softmax", name="output_layer"))

  return model

Hoeveel parameters zal het model hebben?

- Eerste laag: verbindt 4 neuronen met 5 neuronen -> 25 parameters (20 verbindingen en 5 bias parameters)
- Tweede laag: 18 parameters (15 + 3)

Totaal: 43 parameters

In [15]:
model = get_model()
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ hidden_layer (Dense)            │ (None, 5)              │            25 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output_layer (Dense)            │ (None, 3)              │            18 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 43 (172.00 B)

 Trainable params: 43 (172.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
X_batch = X[:2]
X_batch

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [19]:
model(X_batch)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.6999124e-04, 9.9832588e-01, 1.5041083e-03],
       [4.2164593e-04, 9.9718732e-01, 2.3910159e-03]], dtype=float32)>

We beginnen bij 2 bij 4 en gaan naar 2 bij 5 en uiteindelijk 2 bij 3.

2 zal niet veranderen want dat is het aantal instances.

Hoe array interpreteren:
- Voor instance 1 is de kans dat het class 1 is = 0.000169, P class 2 = 0.998, P class 3 = 0.0015
- ...

Hoe werkt softmax?

Softmax zet "logits" (willekeurige getallen) om naar een waarschijnlijkheidsverdeling.

Waarschijnlijkheidsverdeling: alle getallen >= 0 en som = 1

In [22]:
# Zonder softmax krijg je deze output voor X1
logits = np.array([5.574026, -1.7056798, -1.7176703])
logits

array([ 5.574026 , -1.7056798, -1.7176703])

In [25]:
# Omzetten naar waarschijnlijkheidsverdeling
np.exp(logits) / np.sum(np.exp(logits))

array([9.98631316e-01, 6.88444797e-04, 6.80239292e-04])

In [26]:
9.98631316e-01 + 6.88444797e-04 + 6.80239292e-04

1.000000000089